import {base,rand,clamp,dist,aim,cellAt,center,note,burst,finish,COLORS} from '../lib/util.mjs';
import {bg,box,text,line,circle,label,bar,eye,gear} from '../lib/draw.mjs';
export const meta={id:'scrap-sumo',title:'Scrap Sumo',tag:'BUILD & BATTLE',players:4,color:'#f19b7c',description:'Build a toy fighter from wheels, springs, fans, weights, and sticky pads. Push rivals out of the ring.',controls:'During building: choose parts and tap the 3×3 chassis; press Ready. During battle: steer toward a target, Dash into rivals, Reverse, or Brake.',actions:['Mount / dash','Ready / reverse','Remove / brake'],tools:['Wheel','Spring','Fan','Weight','Sticky pad'],tapAction:true,goal:'Win a best-of-three toy-sumo tournament.',ai:'Bots build functional chassis, pursue opponents, dash at contact range, and steer away from the edge.'};
const BX=320,BY=182,BZ=102;
const colors=['#e5b277','#cd9ddb','#91c7dd','#a3b5c0','#9fd1a3'],names=['WHEEL','SPRING','FAN','WEIGHT','STICKY'];
function stats(p){const n=t=>p.parts.filter(x=>x===t).length;return {mass:1+n(3)*.32,thrust:120+n(0)*23+n(2)*14,dash:210+n(1)*65,drag:n(4)*.3};}
function startRound(s){s.phase='battle';s.roundTime=35;s.players.forEach((p,i)=>{p.x=480+Math.cos(i*Math.PI/2)*140;p.y=345+Math.sin(i*Math.PI/2)*140;p.vx=0;p.vy=0;p.alive=true;p.cooldown=0;});note(s,`Round ${s.round}: push the other toys out of the ring.`);}
export function init(seed){const s=base(seed,4,210,2);s.phase='build';s.buildTime=35;s.round=1;s.wait=0;s.players.forEach((p,i)=>Object.assign(p,{parts:Array(9).fill(-1),ready:false,vx:0,vy:0,alive:true,wins:0}));note(s,'Install up to eight parts, then press Ready. The middle square is your core.');return s;}
export function update(s,inputs,dt){
 if(s.phase==='build'){s.buildTime-=dt;s.players.forEach((p,i)=>{const input=inputs[i]||{};if(Number.isInteger(input.tool))p.tool=clamp(input.tool,0,4);const cell=cellAt(input,BX,BY,BZ,3,3);if(input.a&&cell>=0&&cell!==4&&!p.ready)p.parts[cell]=p.tool;if(input.c&&cell>=0&&cell!==4&&!p.ready)p.parts[cell]=-1;if(input.b){if(p.parts.every(v=>v<0))p.parts[7]=0;p.ready=true;}});if(s.players.every(p=>p.ready)||s.buildTime<=0)startRound(s);return;}
 if(s.phase==='between'){s.wait-=dt;if(s.wait<=0){s.round++;startRound(s);}return;}
 s.roundTime-=dt;
 s.players.forEach((p,i)=>{if(!p.alive)return;const input=inputs[i]||{},a=stats(p);let dx=input.dx||0,dy=input.dy||0;if(!dx&&!dy&&input.target){dx=input.target.x-p.x;dy=input.target.y-p.y;}const d=Math.hypot(dx,dy);if(d>3){dx/=d;dy/=d;p.vx+=dx*a.thrust*dt;p.vy+=dy*a.thrust*dt;p.angle=Math.atan2(dy,dx);}
  if(input.a&&p.cooldown<=0){p.vx+=Math.cos(p.angle||0)*a.dash;p.vy+=Math.sin(p.angle||0)*a.dash;p.cooldown=3;burst(s,p.x,p.y,'BOOST',COLORS[i]);}
  if(input.b&&p.cooldown<=0){p.vx*=-.8;p.vy*=-.8;p.cooldown=.4;}
  const drag=input.c?6:1.1+a.drag;p.vx*=Math.exp(-drag*dt);p.vy*=Math.exp(-drag*dt);p.x+=p.vx*dt;p.y+=p.vy*dt;if(Math.hypot(p.x-480,p.y-345)>242){p.alive=false;burst(s,p.x,p.y,'OUT','#ff9c92');}
 });
 for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=s.players[i],b=s.players[j];if(!a.alive||!b.alive)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d<61&&d>.01){const nx=dx/d,ny=dy/d,over=61-d;a.x-=nx*over/2;a.y-=ny*over/2;b.x+=nx*over/2;b.y+=ny*over/2;const velocity=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;const impulse=Math.max(0,velocity)*1.5+45;a.vx-=nx*impulse/stats(a).mass;a.vy-=ny*impulse/stats(a).mass;b.vx+=nx*impulse/stats(b).mass;b.vy+=ny*impulse/stats(b).mass;}}
 const living=s.players.map((p,i)=>({...p,i})).filter(p=>p.alive);if(living.length<=1||s.roundTime<=0){let winner=living.length===1?living[0].i:living.sort((a,b)=>dist(a,{x:480,y:345})-dist(b,{x:480,y:345}))[0]?.i;
  if(winner!=null){s.players[winner].wins++;note(s,`Player ${winner+1} wins round ${s.round}.`);}s.score=s.players[0].wins;
  const champion=s.players.findIndex(p=>p.wins>=2);if(champion>=0||s.round>=5){s.winner=champion>=0?champion:s.players.map((p,i)=>({i,w:p.wins})).sort((a,b)=>b.w-a.w)[0].i;finish(s,true,`Player ${s.winner+1} wins the scrap tournament!`);}else{s.phase='between';s.wait=3;}
 }
}
export function bot(s,i){const p=s.players[i];if(s.phase==='build'){if(p.ready)return{};const cell=p.parts.findIndex((v,j)=>v<0&&j!==4);if(cell<0)return {b:true};const pt=center(cell,BX,BY,BZ,3);return aim(pt.x,pt.y,{a:true,tool:[0,1,3,2,4][(cell+i)%5]});}if(!p.alive)return{};if(dist(p,{x:480,y:345})>174)return aim(480,345,{c:dist(p,{x:480,y:345})>215});const other=s.players.filter((q,j)=>j!==i&&q.alive).sort((a,b)=>dist(p,a)-dist(p,b))[0];return other?aim(other.x,other.y,{a:dist(p,other)<105}):aim(480,345);}
export function hint(s){return s.phase==='build'?'Wheels add thrust. Springs add dash force. Weights resist impacts. Sticky pads add drag.':'Steer back toward the middle before dashing again. Braking helps you survive near the edge.';}
function toy(c,p,i){const a=p.angle||0;c.save();c.translate(p.x,p.y);c.rotate(a);box(c,-25,-22,50,44,COLORS[i],9,'#e6e6c4');for(let j=0;j<9;j++){if(p.parts[j]<0)continue;const x=(j%3-1)*21,y=(Math.floor(j/3)-1)*20;box(c,x-7,y-7,14,14,colors[p.parts[j]],4);}text(c,'›',27,0,27,'#fff6d5','center');c.restore();text(c,p.wins+' WIN'+(p.wins===1?'':'S'),p.x,p.y-47,11,COLORS[i],'center');}
export function render(c,s,view={}){bg(c,'#443b40','#262d38');label(c,s.phase==='build'?'SCRAP WORKSHOP':`SUMO ROUND ${s.round}`,s.phase==='build'?`${Math.ceil(s.buildTime)}s to build • Your chassis is shown below`:`${Math.ceil(s.roundTime||0)} seconds • First to two round wins`);
 if(s.phase==='build'){const p=s.players[view.you??0];box(c,BX-20,BY-20,BZ*3+40,BZ*3+40,'#213444',15,'#829092');for(let i=0;i<9;i++){const x=BX+i%3*BZ,y=BY+Math.floor(i/3)*BZ;box(c,x+4,y+4,BZ-8,BZ-8,i===4?COLORS[view.you??0]:p.parts[i]<0?'#365062':colors[p.parts[i]],10);text(c,i===4?'CORE':p.parts[i]<0?'+':names[p.parts[i]],x+BZ/2,y+BZ/2,i===4?20:p.parts[i]<0?30:12,'#f1edda','center');}text(c,p.ready?'READY FOR THE RING':'YOUR BUILD',480,526,20,'#ebd1ac','center');s.players.forEach((p,i)=>text(c,`P${i+1}: ${p.ready?'READY':p.parts.filter(x=>x>=0).length+' PARTS'}`,65,185+i*48,16,COLORS[i]));}
 else{circle(c,480,351,251,'#102731');circle(c,480,345,239,'#b9a184','#f4d9a3');circle(c,480,345,206,'#b2a487');circle(c,480,345,98,'#bfad8e');for(let i=0;i<8;i++){const a=i*Math.PI/4;line(c,480+Math.cos(a)*213,345+Math.sin(a)*213,480+Math.cos(a)*235,345+Math.sin(a)*235,'#584e45',7);}s.players.forEach((p,i)=>{if(p.alive)toy(c,p,i);});if(s.phase==='between')text(c,s.message,480,340,24,'#333443','center');}
}
